'use client';

import AnimatedCursor from 'react-animated-cursor';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from './components/Footer';
import Navbar from "./components/Navbar";
import Loader from './components/Loader';
import { useEffect, useState } from 'react';
import { usePathname } from 'next/navigation';



// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

const pathname = usePathname();
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    const timer = setTimeout(() => {
      setLoading(false);
    }, 3000); // 3 seconds

    return () => clearTimeout(timer);
  }, [pathname]);





  return (
    <html >
      <body>
        <AnimatedCursor
          innerSize={8}
          outerSize={35}
          color="255, 0, 102"
          outerAlpha={0.2}
          innerScale={1}
          outerScale={2}
          trailingSpeed={6}
          showSystemCursor={false}
        />
        <Navbar />
        {loading ? <Loader /> : children}
        <Footer />
        
      </body>
    </html>
  );
}
