import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from './components/Footer';
import Navbar from "./components/Navbar/page";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html >
      <body>
        <Navbar/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
